################################################################################
# \file bsp.mk
#
# \brief
# Define the CYW955913EVK-01 target.
#
################################################################################
# \copyright
# Copyright 2021-2022 Cypress Semiconductor Corporation (an Infineon company) or
# an affiliate of Cypress Semiconductor Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

ifeq ($(WHICHFILE),true)
$(info Processing $(lastword $(MAKEFILE_LIST)))
endif

# Additional devices on the board
#    If you change the additional device here you must also update the design.modus file and re-run
#    the device configurator. You may also need to update the COMPONENT variable to include the
#    correct Wi-Fi and Bluetooth firmware.

LIFE_CYCLE_STATE?=DM

#Flash build
DIRECT_LOAD=0

BSP_COMPONENTS:=CYW955913SDCM2WLIPA

# this is need for picking the secure/non secure Firmware image
ifeq ($(LIFE_CYCLE_STATE),DM)
BSP_COMPONENTS+=SM
else
BSP_COMPONENTS+=CM
endif

# App preferred execution memory
# use flash, psram, or ram
APPEXEC?=flash

# linker script template
BSP_LINKER_SCRIPT_PATH=$(MTB_TOOLS__TARGET_DIR)/TOOLCHAIN_$(TOOLCHAIN)
BSP_LINKER_SCRIPT=$(BSP_LINKER_SCRIPT_PATH)/$(CHIP_NAME)_$(APPEXEC).$(MTB_RECIPE__SUFFIX_LS)

# Select between the shared and dedicated LNA / ANT paths. 
# The three options are SLNA_ANT0, DLNA_BTANT and DLNA_ANT0.
CHIP_ANT_SEL:=SLNA_ANT0

# Additional WiFi country code.
BSP_DEFINES+=CY_USING_HAL CY_STORAGE_WIFI_DATA=\".cy_xip\"
ifeq ($(filter CY_WIFI_COUNTRY%,$(DEFINES)),)
BSP_DEFINES+=CY_WIFI_COUNTRY='WHD_COUNTRY_UNITED_STATES'
endif

################################################################################
# ALL ITEMS BELOW THIS POINT ARE AUTO GENERATED BY THE BSP ASSISTANT TOOL.
# DO NOT MODIFY DIRECTLY. CHANGES SHOULD BE MADE THROUGH THE BSP ASSISTANT.
################################################################################

# Board device selection. MPN_LIST tracks what was selected in the BSP Assistant
# All other variables are derived by BSP Assistant based on the MPN_LIST.
MPN_LIST:=CYW55913IUBGT

# Device specific components picked up by pdl-cat5.mk file
DEVICE_COMPONENTS:=55900 55900A0 CAT5 NETXDUO NETXSECURE NETXSECURE_ROM THREADX WIFI_INTERFACE_OCI

-include $(SEARCH_mtb-pdl-cat5)/devices/pdl-cat5.mk
DEVICE:=CYW55913IUBGT
DEVICE_CYW55913IUBGT_CORES:=CORE_NAME_CM33_0
DEVICE_CYW55913IUBGT_DIE:=55900A0
DEVICE_CYW55913IUBGT_FLASH_KB:=0
DEVICE_CYW55913IUBGT_SRAM_KB:=768
DEVICE_DEFINES:=BLHS_SUPPORT GCI_SECURE_ACCESS MBEDTLS_CONFIG_FILE='"mbedtls/config-cc312-h1cp-no-os.h"' NX_INCLUDE_USER_DEFINE_FILE NX_SECURE_INCLUDE_USER_DEFINE_FILE PROTO_MSGBUF TRXV5
DEVICE_LIST:=CYW55913IUBGT
DEVICE_TOOL_IDS:=bsp-assistant bt-configurator device-configurator library-manager project-creator
RECIPE_DIR:=$(SEARCH_recipe-make-cat5)
